### PR TITLE
2022.05.19 crossword

### PR DESCRIPTION
**Pull request by roygbyte**
Updates crossword repo to latest version, which includes a bug fix and introduces the "reveal square" game menu item.

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/contrib/17)

### CODE REVIEW

**Comment by Frenzie** [comment]
@poire-z What did you say your preferred way of rebasing was?

**Comment by poire-z** [comment]
In which context ? Via github or command line ?
Anyway, here it looks like just a submodule bump, so probably better just redone.
And here, it's just the first 2 commits that are old and already merged.
So, I would probably do:
```
$ git checkout master
$ git fetch upstream
$ git merge upstream/master
$ git push origin master
$ git checkout 2022.05.19-crossword
$ git rebase origin/master
```
and I guess it should notice the presence of the 2 first commits and drop them.
If not, drop the 2 commits and create a new one:
```
git reset HEAD~3
git add crossword.koplugin
git commit -v
```

**Comment by roygbyte** [comment]
I do not understand this conflict. `crossword.kolpugin` is the plugin folder.

**Comment by Frenzie** [comment]
That would mean your branch deviated from this repo in that regard. You'll need to merge or rebase using @poire-z's instructions or the ones from GitHub.

**Comment by Frenzie** [comment]
That seems to have worked. :+1: All ready for merge? And which instructions did you use?

**Comment by roygbyte** [comment]
Woooooo 🎉

Yes, were ready captain. 

@poire-z instructions paved the way...

**Pull request merged**
