### PR TITLE
analog clock plugin

### PR DESCRIPTION
**Pull request by jperon**
As is, it integrates [MoonScript](http://moonscript.org). It would be possible to "pre-compile" `.moon` files to `.lua` and get rid of the `moonscript` directory and `moonscript.lua`.

I don’t think [insert_menu](https://github.com/koreader/koreader/blob/master/frontend/ui/plugin/insert_menu.lua?rgh-link-date=2021-05-12T00%3A23%3A53Z) is necessary for it, as it’s already handled in `clock.moon` (l. 42-43).

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/contrib/2)

### CODE REVIEW

**Comment by Frenzie** [comment]
> It would be possible to "pre-compile" .moon files to .lua and get rid of the moonscript directory and moonscript.lua.

Why not both? Moonscript is easily installed using luarocks so it hardly seems necessary to bundle the whole thing.

**Comment by jperon** [comment]
In fact, I think the best way would be to integrate only the pre-compiled `.lua` files in this repository, with the `Readme` directing users to https://github.com/jperon/clock.koplugin for issues. This would keep the "released" version here, simple (to install) & small (without moonscript dependency), and the "source" there. Any thoughts ?

**Comment by Frenzie** [comment]
I see no problem with simply referring back to the moonscript source in the plugin's README file and perhaps a little comment at the top of the file too.

**Comment by jperon** [comment]
Just force-pushed the changes.

**Comment by Frenzie** [comment]
Cool, thanks!

**Comment by Hzj-jie** [comment]
Thank you.

**Pull request merged**
